### PR TITLE
Allow null description from API, fixes #6

### LINKED ISSUE #6: Issues with no description fail to unfurl since v0.6.0
Hi, 

The fixes for #2 introduces a regression: If an issue doesn't have a description set, it will fail to unfurl with the following error:

```
[2018-10-19 18:38:03] unfurl.ERROR: Uncaught Exception TypeError: "Argument 1 passed to GitlabSlackUnfurl\Route\AbstractRouteHandler::sanitizeText() must be of the type string, null given, called in /app/vendor/glen/slack-unfurl-gitlab/src/Route/Issue.php on line 24" at /app/vendor/glen/slack-unfurl-gitlab/src/Traits/SanitizeTextTrait.php line 7 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to GitlabSlackUnfurl\\Route\\AbstractRouteHandler::sanitizeText() must be of the type string, null given, called in /app/vendor/glen/slack-unfurl-gitlab/src/Route/Issue.php on line 24 at /app/vendor/glen/slack-unfurl-gitlab/src/Traits/SanitizeTextTrait.php:7)"} []
```

I checked the code the commit that breaks it is: https://github.com/glensc/slack-unfurl-gitlab/pull/5/commits/8cd3b212097605c39159cb62021fce409a02edaf

Specifically here: https://github.com/glensc/slack-unfurl-gitlab/pull/5/commits/8cd3b212097605c39159cb62021fce409a02edaf#diff-7e2b8567c9d59205b305dc51a0d3b4cdR7 because it expects a string no matter what. 

Thanks!

### PR DESCRIPTION
**Pull request by glensc**
Altho could not reproduce this with actual api query. i've mocked `null` result and committed the fix.

cc @joelsdc

### CODE REVIEW

**Comment by glensc** [comment]
@joelsdc if you are able to reproduce this in gitlab.com and give api url. would be awesome, for me the url was `description: ""` not `description: null`

https://gitlab.com/api/v4/projects/glensc%2fplayground/issues?iids%5B%5D=1

ps: seems projects api is allowed anonymous access for some odd reason ;)

**Comment by joelsdc** [comment]
Hi @glensc, unfortunately we have a hosted GitLab server so it could be very possible that this only happens on self-hosted servers, and in gitlab.com the behavior is different.

**Comment by joelsdc** [comment]
Hi @glensc in fact I just verified, on gitlab-starter edition self hosted:

```
{  
   id:277,
   iid:119,
   project_id:1,
   title:"GKE PRD deployments notify in #ops too",
   description:null,
   state:"opened",
   created_at:"2018-09-25T18:53:33.400Z",
   updated_at:"2018-09-25T18:53:33.900Z",
   closed_at:null,
   closed_by:null,
   labels:[  
      "To Do"
   ],
   milestone:null,
   assignees:[  

   ],
   author:{  
      id:3,
      name:"test",
      username:"test",
      state:"active",
      avatar_url:"https://git.domain.com/uploads/-/system/user/avatar/3/avatar.png",
      web_url:"https://git.domain.com/test"
   },
   assignee:null,
   user_notes_count:0,
   upvotes:0,
   downvotes:0,
   due_date:null,
   confidential:false,
   discussion_locked:null,
   web_url:"https://git.domain.com/group/test-devops/issues/119",
   time_stats:{  
      time_estimate:0,
      total_time_spent:0,
      human_time_estimate:null,
      human_total_time_spent:null
   },
   _links:{  
      self:"https://git.domain.com/api/v4/projects/1/issues/119",
      notes:"https://git.domain.com/api/v4/projects/1/issues/119/notes",
      award_emoji:"https://git.domain.com/api/v4/projects/1/issues/119/award_emoji",
      project:"https://git.domain.com/api/v4/projects/1"
   },
   subscribed:false,
   weight:null
}
```

**Comment by glensc** [comment]
could be that gitlab.com is just using newer version, or just different version

you can see the version from api url: https://gitlab.com/api/v4/version

**Comment by joelsdc** [comment]
our GitLab hosted:

```
{
  version: "11.3.4-ee",
  revision: "14d3a1d"
}
```

online GitLab.com:

```
{
  version: "11.4.0-ee",
  revision: "cfe266c"
}
```

I'll update our server and re-test tomorrow. I'm curious if they are just different codebases or if this small thing is fixed on v11.4.0

😂😂😂

**Pull request merged**
